name: Publish the package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  jsr:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-jsr
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22
          package-manager-cache: false
      - run: pnpm install
      - name: Publish package
        run: pnpm dlx jsr publish
  npm:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: https://registry.npmjs.org
      - name: Update npm
        run: npm install -g npm@latest
      - name: Check npm version (for debug)
        run: npm -v
      - run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish package
        # https://github.com/pnpm/pnpm/issues/5894
        run: pnpm publish --no-git-checks
