name: Publish the package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  jsr:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - name: Publish package
        run: pnpm dlx jsr publish
  npm:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
    permissions:
      contents: read
      id-token: write
    environment: npm
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish package
        run: pnpm publish
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
